### ISSUE TITLE
使用 pnpm 安装 webpack 扩展出错

### ISSUE THREAD

**Issue by zcf0508** [zh-lx/code-inspector#25]
```shell
> pnpm install webpack-code-inspector-plugin --save-dev


ERR_PNPM_WORKSPACE_PKG_NOT_FOUND  In : "code-inspector-core@workspace:*" is in the dependencies but no package named "code-inspector-core" is present in the workspace

This error happened while installing the dependencies of webpack-code-inspector-plugin@0.0.6
```

**Comment by zh-lx** [comment]
感谢反馈，发包时用错包管理器了，已经修复，请安装 `0.0.7` 版本试一试

**Comment by raDiesle** [comment]
Hi,
when using yarn with pnpm and switching from 0.20.16 to 1.1.0 it fails with:


Y@MacBook-Pro-von-Yui % ./yarn install
➤ YN0000: · Yarn 4.8.1
➤ YN0000: ┌ Resolution step
➤ YN0001: │ Error: @code-inspector/core@workspace:*: Workspace not found (@code-inspector/core@workspace:*)
    at t.getWorkspaceByDescriptor (/Users/Y/IdeaProjects/react-ui/ui/.yarn/releases/yarn-4.8.1.cjs:210:3520)
    at t.getCandidates (/Users/Y/IdeaProjects/react-ui/ui/.yarn/releases/yarn-4.8.1.cjs:140:117091)
    at xg.getCandidates (/Users/Y/IdeaProjects/react-ui/ui/.yarn/releases/yarn-4.8.1.cjs:141:1311)
    at xg.getCandidates (/Users/Y/IdeaProjects/react-ui/ui/.yarn/releases/yarn-4.8.1.cjs:141:1311)
    at /Users/Y/IdeaProjects/react-ui/ui/.yarn/releases/yarn-4.8.1.cjs:210:8420
    at Xm (/Users/Y/IdeaProjects/react-ui/ui/.yarn/releases/yarn-4.8.1.cjs:140:53878)
    at gt (/Users/Y/IdeaProjects/react-ui/ui/.yarn/releases/yarn-4.8.1.cjs:210:8400)
    at async Promise.allSettled (index 0)
    at async Wc (/Users/Y/IdeaProjects/react-ui/ui/.yarn/releases/yarn-4.8.1.cjs:140:53206)
